### ISSUE TITLE
Is this necessary?

### ISSUE THREAD

**Issue by madjam002** [pact-foundation/pact-provider-verifier#1]
Can this functionality not be merged into the original ruby implementation of Pact?

It just seems that the Pact community is extremely fragmented at the moment with various different repos cropping up all trying to do the same thing, I'm thinking it would be best if this kind of functionality could go in Pact itself.

Please fill me in if there is something that I am missing 😕

**Comment by uglyog** [comment]
This project aims to provide verification of pacts for languages other than Ruby, so having it as a separate repo and package kind of makes sense.

**Comment by mefellows** [comment]
Apologies I didn't see this earlier @madjam002, I've been fairly active on this recently too!

I agree, it's confusing. Without going into detail, there are pros and cons of putting this in the upstream Pact repository. Mainly, if you are using Ruby you _do not need this_ and it's just extra baggage.

In an ideal world this package wouldn't exist. In fact, it simply wraps the verification library in Pact into a 'binary' (I use the term loosely here) so that it can be embedded in other language implementations (see https://github.com/pact-foundation/pact-js and https://github.com/pact-foundation/pact-go). 

Unless you have a good reason to use this, I wouldn't.

Perhaps the best thing to do is update the README/docs to make it less confusing - I can certainly see how this could/would be confusing to others.

**Comment by madjam002** [comment]
@mefellows Thanks for getting back to me!
I haven't done any Pact work in the past couple of weeks so excuse my ignorance if I've got this completely wrong :smile:

From my understanding, the main feature of this tool is that it wraps the original Pact library allowing you to configure your provider states over HTTP instead of just invoking some Ruby implementation, meaning you can work with any language in theory because you can just implement the provider state server in a language of your choosing.

So I guess my original point was, can we contribute the ability to call a provider state HTTP server instead of invoking Ruby code to the original Pact library instead of implementing it here?

We're running Pact inside a Docker container anyway so the fact that it is ruby isn't so much of a problem, it's just the provider states needing to be in Ruby which is causing the issue.

Thanks for your time, I'd be interested to know what you're thoughts are. 😃

**Comment by mefellows** [comment]
No worries at all.

Actually, this library really only does one thing: wrap up the (language independent) pact verification process into a "binary" that can be used cross-platform and without installing a ruby runtime (I'm using air quotes because Ruby doesn't really have the concept, and we are really wrapping up an entire Ruby runtime for each OS).

The feature you're referring to is actually implemented here: https://github.com/bethesque/pact-provider-proxy and has been around for ages.

But that is somewhat skirting your question. Why isn't the `pact-provider-proxy` feature in Pact proper? 

Well, I can't answer for sure, but my guess is that even if it was you would still need a library like this to make it Ruby independent. And if you are using Ruby, you can simply add that gem to the project and with minimal configuration (basically setup the rake task) you get it anyway.

On a related note, we recognise this fragmentation and are trying to resolve it [1,2]. The unfortunate situation is that in the process of resolving it, we are ironically adding _more_ (https://xkcd.com/927/).

It's probably not the most satisfying answer, but it is an honest one!

1. docs.pact.io/roadmap/
2. https://github.com/pact-foundation/pact-reference/

**Comment by madjam002** [comment]
@mefellows That sounds great, thanks for the extensive answer. The roadmap seems to be what I was after 😊

**Comment by mefellows** [comment]
👍
