### ISSUE TITLE
Cannot publish verification results to broker behind reverse proxy

### ISSUE THREAD

**Issue by pastap** [pact-foundation/pact-provider-verifier#20]
Hi,

I've set up a broker behind an nginx reverse proxy for https.  As per [the broker documentation](https://github.com/pact-foundation/pact_broker/wiki/Configuration#running-the-broker-behind-a-reverse-proxy), requests to the broker should be made with header: `{"X-Forwarded-Scheme": "https"}`.

When specifying an `https` pact url to the verifier, without this header, the metadata of the pact file includes
```
"pb:publish-verification-results": {
   "title": "Publish verification results",
   "href": "http://<URL>:443/pacts/provider/A/consumer/B/pact-version/V123/verification-results"
},
```
note the `http://<URL>:443/`. With the header, this is corrected to `https://<URL>/`
```
"pb:publish-verification-results": {
   "title": "Publish verification results",
   "href": "https://<URL>/pacts/provider/A/consumer/B/pact-version/V123/verification-results"
},
```

So, if the broker is behind a proxy, `pact-provider-verifier` will not specify the necessary header, and get an `http` verification-results link. When publishing the results, this will then fail with:

```
/usr/local/bundle/gems/pact-1.19.2/lib/pact/provider/verification_results/publish.rb:112:in `publish_verification_results': Error returned from verification results publication 400 <html>
 (Pact::Provider::VerificationResults::PublicationError)
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.12.2</center>
</body>
</html>
```

Can an option be added to specify headers to use when interacting with the broker?

**Comment by mefellows** [comment]
No, we should just make sure intermediate proxies are indeed sending through the correct headers or fix the broker if there is an issue.

I know for a fact that it works because that is how we do it for the hosted broker at pact.dius.com.au

Is there any logging we can output to ensure the right headers are coming thru? The proxy we use passes through all of the headers in the docs you note.

**Comment by bethesque** [comment]
Here is the documentation for setting up the headers when you are running a reverse proxy over https: https://github.com/pact-foundation/pact_broker/wiki/Configuration#running-the-broker-behind-a-reverse-proxy

**Comment by bethesque** [comment]
I'm not sure from your description if you are adding the headers manually in the request, or if you are adding the headers in the nginx configuration. Can you confirm @pastap?

**Comment by bethesque** [comment]
I believe it's this config, but someone correct me if I'm wrong: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

**Comment by mefellows** [comment]
@pastap please see https://github.com/DiUS/pact_broker-docker/issues/58#issuecomment-358819665 for a working example with nginx. As per @bethesque's comment, these headers must be present in the proxy configuration so that the headers are passed on to the broker, not your request _to_ the proxy. Closing, as we can demonstrate that this works.

**Comment by pastap** [comment]
I was adding the headers manually, and therefore expected a way to pass on these headers using the tool. However, adding proxy headers to the nginx conf makes sense; thank you @bethesque and @mefellows for your help. I'll give that a whirl!

**Comment by mefellows** [comment]
No worries!
