### ISSUE TITLE
Mistake in release notes

### ISSUE THREAD

**Issue by adambeben** [pact-foundation/pact-provider-verifier#34]
In release notes, under "To install and run on Windows" there is one command:
`.\bin\pact-mock-service.bat -p 1234`
Which is not related to pact-provider-verifier.

**Comment by YOU54F** [comment]
Thanks buddy

![Screenshot 2023-05-11 at 21 10 00](https://github.com/pact-foundation/pact-provider-verifier/assets/19932401/9c18d745-7e1f-4882-80a8-338843be051f)

Updated in the above commit, will need to look at the release notes as they have stopped after this release

https://github.com/pact-foundation/pact-provider-verifier/releases/tag/v1.32.1

no release notes

https://github.com/pact-foundation/pact-provider-verifier/releases/tag/v1.33.0

I _think_ this is because the pact-foundation/release-gem doesn't consider the release note templates

https://github.com/pact-foundation/release-gem/blob/cc4b0b5e750acf9d18bd4bc816b3a75b43489788/container/usr/local/bin/generate-release-notes#L8

which is here

https://github.com/pact-foundation/pact-provider-verifier/blob/master/packaging/RELEASE_NOTES.md.template

cc: @bethesque does the release-gem just need a tweak to pick up a custom release note template, if one exists, I had a quick scan and doesn't look like it currently supports it

**Comment by YOU54F** [comment]
Fixed thanks bud
