### ISSUE TITLE
Ignore/Handle Header matching into Pact File

### ISSUE THREAD

**Issue by tanmoy1990** [pact-foundation/pact-provider-verifier#54]
Hello Guys,
As per our requirement, Actual end-point returning lots of information into header along with response message. So I not able to make the header property under **WillResondwith** section of MockEndpoint configure. Please help me to figure out the issue by which I can run the provider test.

Header Information Sending By Actual End-Point ::
![image](https://user-images.githubusercontent.com/44140755/76770715-5e34f000-67c4-11ea-9060-40b0ba9fd30c.png)

**Comment by bethesque** [comment]
I'm sorry, I don't understand the question. Can you please fill in the following template and create an executable example to demonstrate your problem.

# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [ ] Upgraded to the latest version OR
* [ ] Checked the CHANGELOG to see if the issue I am about to raise has been fixed
* [ ] Created an executable example that demonstrates the issue using either a:
  * Dockerfile
  * Git repository with a Travis or Appveyor (or similar) build

## Software versions

* **pact-broker gem version:** eg 2.3.1
* **pact-broker docker version:** eg 2.3.1-1
* **OS**: e.g. Mac OSX 10.11.5
* **pact broker client details:** eg. pact-ruby-standalone CLI v 1.23.0

## Expected behaviour

TBC

## Actual behaviour

TBC

## Steps to reproduce

Provide a repository, gist or reproducible code snippet so that we can test the problem.

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by YOU54F** [comment]
Closing due to lack of response
